baseURL = "https://tomatomaster.github.io/"
languageCode = "ja-jp"
title = "hogehoge"
publishDir = "public"  # 公開ファイルのディレクトリ名
theme= "hugo-classic" # 使用するテーマ名
hasCJKLanguage = true # 記事のサマリー機能を有効にする。trueにしないと記事サマリーの文章量が大きくなりすぎる。
paginate = 10 # 一つのページに何個まで記事を載せるか。
paginatePath = "page"